#!/usr/bin/env node

var pkg = require( '../package.json' );
var program = require( 'commander' );

program
	.version( pkg.version )

	.command( 'config <name>', 'config VVV machine information.' )
	.command( 'wp <site> <command>', 'run a WP-CLI command in the directory of a VVV machine.' )

	.parse( process.argv );
